import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app.x-test2.5-now.com/login');
  await page.getByRole('textbox', { name: 'メールアドレス' }).click();
  await page.locator('div').filter({ hasText: '会社コード/ユーザーコードを使用 ⇨ ログイン' }).nth(1).click();
  await page.getByRole('textbox', { name: 'メールアドレス' }).click();
  await page.getByRole('textbox', { name: 'メールアドレス' }).click();
  await page.getByRole('textbox', { name: 'メールアドレス' }).fill('itomariko88@gmail.com');
  await page.getByRole('textbox', { name: 'メールアドレス' }).press('Tab');
  await page.getByRole('textbox', { name: 'パスワード' }).fill('Password012345@');
  await page.getByRole('button', { name: 'ログイン' }).click();
  await page.getByRole('link', { name: 'グループ グループ' }).click();
  await page.getByRole('button', { name: 'kanban グループ/エリア 登録' }).click();
  await page.getByRole('radio', { name: 'エリア' }).check();
  await page.getByRole('textbox', { name: '名称' }).click();
  await page.getByRole('textbox', { name: '名称' }).fill('エリアB-1');
  await page.getByRole('textbox', { name: '所属' }).click();
  await page.getByRole('option', { name: 'グループmito_B' }).click();
  await page.getByRole('button', { name: '登録', exact: true }).click()

  await page.getByRole('button', { name: 'kanban グループ/エリア 登録' }).click();
  await page.getByRole('textbox', { name: '名称' }).click();
  await page.getByRole('textbox', { name: '名称' }).fill('グループB-1');
  await page.getByRole('textbox', { name: '所属' }).click();
  await page.getByRole('option', { name: 'グループmito_B' }).click();
  await page.getByRole('textbox', { name: '住所' }).click();
  await page.getByRole('textbox', { name: '住所' }).fill('北海道札幌市');
  await page.getByText('※ 名称 ※ 所属 十字じゅうじキーで選択せんたく、文字入力文字入力でフィルター 担当 十字じゅうじキーで選択せんたく、文字入力文字入力でフィルター 電話番号 ').click();
  await page.getByRole('button', { name: '登録', exact: true }).click();
  await page.goto('https://app.x-test2.5-now.com/groups/68fe857b-e2eb-4ec8-b93a-ae2ed4de45ec');
  await page.getByRole('button', { name: 'icon グループB-' }).click();
  await page.getByRole('button', { name: 'kanban グループ/エリア 登録' }).click();
  await page.getByRole('radio', { name: 'エリア' }).check();
  await page.getByRole('textbox', { name: '名称' }).click();
  await page.getByRole('textbox', { name: '名称' }).fill('エリアB-1-1');
  await page.getByRole('textbox', { name: '所属' }).click();
  await page.getByRole('option', { name: 'グループB-' }).click();
  await page.getByRole('button', { name: '登録', exact: true }).click();
  await page.getByRole('button', { name: 'icon エリアB-1-' }).click();
  await page.getByRole('button', { name: 'kanban グループ/エリア 登録' }).click();
  await page.getByRole('textbox', { name: '名称' }).click();
  await page.getByRole('textbox', { name: '名称' }).fill('グループB-1-1-1');
  await page.getByRole('textbox', { name: '所属' }).click();
  await page.getByRole('option', { name: 'グループB-' }).click();
  await page.getByRole('textbox', { name: '住所' }).click();
  await page.getByRole('textbox', { name: '住所' }).fill('ほ');
  await page.getByRole('textbox', { name: '住所' }).click();
  await page.getByRole('textbox', { name: '住所' }).fill('北海道札幌市');
  await page.getByRole('button', { name: '登録', exact: true }).click();
  await page.goto('https://app.x-test2.5-now.com/groups/ba79aeb6-4dec-4093-8877-158679e0ab86');
  await page.getByRole('button', { name: 'icon グループmito_B ▼' }).click();
  await page.getByRole('button', { name: 'icon グループB-1 ▼' }).click();
  await page.getByRole('button', { name: 'icon グループB-1-1-' }).click();
  await page.getByRole('button', { name: 'kanban グループ/エリア 登録' }).click();
  await page.getByRole('radio', { name: 'エリア' }).check();
  await page.getByRole('textbox', { name: '名称' }).click();
  await page.getByRole('textbox', { name: '名称' }).fill('エリアB-1-1-1-1');
  await page.getByRole('textbox', { name: '所属' }).click();
  await page.getByRole('option', { name: 'グループB-1-1-' }).click();
  await page.getByRole('button', { name: '登録', exact: true }).click();
  await page.goto('https://app.x-test2.5-now.com/groups/491fbd29-4ddc-48a9-88fd-928c9532a8f6');
    await page.getByRole('button', { name: 'icon エリアB-1-1-1-' }).click();
  });